//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crop()
        {
            this.bids = new HashSet<bid>();
        }
    
        public int CID { get; set; }
        public string crop_name { get; set; }
        public string crop_type { get; set; }
        public string fertilizer_type { get; set; }
        public int quantity { get; set; }
        public Nullable<int> base_price { get; set; }
        public Nullable<double> sold_price { get; set; }
        public Nullable<int> approved { get; set; }
        public Nullable<int> sold { get; set; }
        public Nullable<System.DateTime> date_sold { get; set; }
        public Nullable<double> current_bid { get; set; }
        public string bidder_name { get; set; }
        public int UID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bid> bids { get; set; }
        public virtual user user { get; set; }
    }
}
