//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int imgID { get; set; }
        public string imgCaption { get; set; }
        public string imgName { get; set; }
        public int UID { get; set; }
    
        public virtual user user { get; set; }
    }
}
